### ISSUE TITLE
Dropdown del combobox grigio e non nero

### ISSUE THREAD

**Issue by nikonik99** [nikonik99/sitoFurti#3]
Il dropdown del combobox risulta grigio e poco leggibile

Screenshot:
![schermata del 2017-07-26 14 04 07](https://user-images.githubusercontent.com/23040549/28620001-623db1ca-720b-11e7-81ec-e05894d37cad.png)

**Comment by manuelbarusco** [comment]
risolto con l'aggiunta di stili al tag option nell'ultimo commit
